services:
  - type: web
    name: mari-milkat-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ADMIN_EMAIL
        value: marimilkatadmin@gmail.com
      - key: ADMIN_PASSWORD
        value: Admin@MariMilkat
      - key: GMAIL_USER
        value: marimilkat@gmail.com
      - key: GMAIL_PASS
        value: gsxagfmavwsifbrm
      - key: SUPABASE_URL
        value: https://osowusrcwpqqxhcjzaom.supabase.co
      - key: SUPABASE_KEY
        value: sb_secret_GFznab4LrrKUNbroT2QRAA_4SITlv1A
      - key: SUPABASE_STORAGE_BUCKET
        value: property-images
